# @package _global_

# default running mode

default_mode: True
base_outdir: logs

hydra:
  # default output paths for all file logs
  run:
    dir: ${base_outdir}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${base_outdir}/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
