upload_code_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCodeAsArtifact
  code_dir: ${work_dir}/src

upload_ckpts_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCheckpointsAsArtifact
  ckpt_dir: "checkpoints/"
  upload_best_only: False

add_model_metadata_to_config:
  _target_: src.callbacks.wandb_callbacks.AddModelMetadataToConfig

log_layerwise_kls:
  _target_: src.callbacks.wandb_callbacks.LogLayerwiseKLDistributions